### PR TITLE
[#15] add google prettify

### PR DESCRIPTION
**Pull request by kapone89**
I've added google prittify so values other than json will be automatically prettified. WDYT?

[Review on Reviewable](https://reviewable.io/reviews/monterail/redis-browser/17)

### CODE REVIEW

**Comment by kapone89** [comment]
I wanted to user angular filter but I don't know how get raw html in filter in angular 1.0.6. In higher versions there is something like $sce

**Comment by jandudulski** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- lib/redis-browser/public/css/github.css @ r1
- lib/redis-browser/templates/coffee/app.coffee @ r1
- lib/redis-browser/templates/index.slim @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/redis-browser/17)

**Comment by teamon** [comment]
@kapone89 @jandudulski can we merge this?

**Comment by jandudulski** [comment]
I guess yes

**Comment by teamon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/redis-browser/17)

**Comment by teamon** [comment]
Let's do it then :)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/redis-browser/17)

**Pull request merged**
